/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BuscaRouteImport } from './routes/busca'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as PagamentoEFreteRouteImport } from './routes/pagamento-e-frete'
import { Route as PoliticaDePrivacidadeRouteImport } from './routes/politica-de-privacidade'
import { Route as QuemSomosRouteImport } from './routes/quem-somos'
import { Route as TrocasEDevolucoesRouteImport } from './routes/trocas-e-devolucoes'
import { Route as CategoriaSlugRouteImport } from './routes/categoria.$slug'
import { Route as ProdutosIndexRouteImport } from './routes/produtos.index'
import { Route as ProdutosSlugRouteImport } from './routes/produtos.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscaRoute = BuscaRouteImport.update({
  id: '/busca',
  path: '/busca',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const PagamentoEFreteRoute = PagamentoEFreteRouteImport.update({
  id: '/pagamento-e-frete',
  path: '/pagamento-e-frete',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadeRoute = PoliticaDePrivacidadeRouteImport.update({
  id: '/politica-de-privacidade',
  path: '/politica-de-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const QuemSomosRoute = QuemSomosRouteImport.update({
  id: '/quem-somos',
  path: '/quem-somos',
  getParentRoute: () => rootRouteImport,
} as any)
const TrocasEDevolucoesRoute = TrocasEDevolucoesRouteImport.update({
  id: '/trocas-e-devolucoes',
  path: '/trocas-e-devolucoes',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriaSlugRoute = CategoriaSlugRouteImport.update({
  id: '/categoria/$slug',
  path: '/categoria/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosIndexRoute = ProdutosIndexRouteImport.update({
  id: '/produtos/',
  path: '/produtos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosSlugRoute = ProdutosSlugRouteImport.update({
  id: '/produtos/$slug',
  path: '/produtos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/busca': typeof BuscaRoute
  '/contato': typeof ContatoRoute
  '/pagamento-e-frete': typeof PagamentoEFreteRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/quem-somos': typeof QuemSomosRoute
  '/trocas-e-devolucoes': typeof TrocasEDevolucoesRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/produtos/$slug': typeof ProdutosSlugRoute
  '/produtos/': typeof ProdutosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/busca': typeof BuscaRoute
  '/contato': typeof ContatoRoute
  '/pagamento-e-frete': typeof PagamentoEFreteRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/quem-somos': typeof QuemSomosRoute
  '/trocas-e-devolucoes': typeof TrocasEDevolucoesRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/produtos/$slug': typeof ProdutosSlugRoute
  '/produtos': typeof ProdutosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/busca': typeof BuscaRoute
  '/contato': typeof ContatoRoute
  '/pagamento-e-frete': typeof PagamentoEFreteRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/quem-somos': typeof QuemSomosRoute
  '/trocas-e-devolucoes': typeof TrocasEDevolucoesRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/produtos/$slug': typeof ProdutosSlugRoute
  '/produtos/': typeof ProdutosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/busca'
    | '/contato'
    | '/pagamento-e-frete'
    | '/politica-de-privacidade'
    | '/quem-somos'
    | '/trocas-e-devolucoes'
    | '/categoria/$slug'
    | '/produtos/$slug'
    | '/produtos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/busca'
    | '/contato'
    | '/pagamento-e-frete'
    | '/politica-de-privacidade'
    | '/quem-somos'
    | '/trocas-e-devolucoes'
    | '/categoria/$slug'
    | '/produtos/$slug'
    | '/produtos'
  id:
    | '__root__'
    | '/'
    | '/busca'
    | '/contato'
    | '/pagamento-e-frete'
    | '/politica-de-privacidade'
    | '/quem-somos'
    | '/trocas-e-devolucoes'
    | '/categoria/$slug'
    | '/produtos/$slug'
    | '/produtos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuscaRoute: typeof BuscaRoute
  ContatoRoute: typeof ContatoRoute
  PagamentoEFreteRoute: typeof PagamentoEFreteRoute
  PoliticaDePrivacidadeRoute: typeof PoliticaDePrivacidadeRoute
  QuemSomosRoute: typeof QuemSomosRoute
  TrocasEDevolucoesRoute: typeof TrocasEDevolucoesRoute
  CategoriaSlugRoute: typeof CategoriaSlugRoute
  ProdutosSlugRoute: typeof ProdutosSlugRoute
  ProdutosIndexRoute: typeof ProdutosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/busca': {
      id: '/busca'
      path: '/busca'
      fullPath: '/busca'
      preLoaderRoute: typeof BuscaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagamento-e-frete': {
      id: '/pagamento-e-frete'
      path: '/pagamento-e-frete'
      fullPath: '/pagamento-e-frete'
      preLoaderRoute: typeof PagamentoEFreteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidade': {
      id: '/politica-de-privacidade'
      path: '/politica-de-privacidade'
      fullPath: '/politica-de-privacidade'
      preLoaderRoute: typeof PoliticaDePrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quem-somos': {
      id: '/quem-somos'
      path: '/quem-somos'
      fullPath: '/quem-somos'
      preLoaderRoute: typeof QuemSomosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trocas-e-devolucoes': {
      id: '/trocas-e-devolucoes'
      path: '/trocas-e-devolucoes'
      fullPath: '/trocas-e-devolucoes'
      preLoaderRoute: typeof TrocasEDevolucoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categoria/$slug': {
      id: '/categoria/$slug'
      path: '/categoria/$slug'
      fullPath: '/categoria/$slug'
      preLoaderRoute: typeof CategoriaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos/': {
      id: '/produtos/'
      path: '/produtos'
      fullPath: '/produtos/'
      preLoaderRoute: typeof ProdutosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos/$slug': {
      id: '/produtos/$slug'
      path: '/produtos/$slug'
      fullPath: '/produtos/$slug'
      preLoaderRoute: typeof ProdutosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuscaRoute: BuscaRoute,
  ContatoRoute: ContatoRoute,
  PagamentoEFreteRoute: PagamentoEFreteRoute,
  PoliticaDePrivacidadeRoute: PoliticaDePrivacidadeRoute,
  QuemSomosRoute: QuemSomosRoute,
  TrocasEDevolucoesRoute: TrocasEDevolucoesRoute,
  CategoriaSlugRoute: CategoriaSlugRoute,
  ProdutosSlugRoute: ProdutosSlugRoute,
  ProdutosIndexRoute: ProdutosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
